descricao_origens = {
    "Acadêmico": "Você era um pesquisador ou professor universitário.",
    "Agente de Saúde": "Você era um profissional da saúde, como um enfermeiro, farmacêutico, médico, psicólogo ou socorrista.",
    "Amigo dos Animais": "Você desenvolveu uma conexão muito forte com outros seres: os animais.",
    "Amnésico": "Você perdeu a maior parte da memória. Sabe apenas o próprio nome, ou nem isso.",
    "Artista": "Você era um ator, músico, escritor, dançarino, influenciador.",
    "Astronauta": "Como um astronauta, você se acostumou à pressão de ser responsável pela vida de seus colegas e por experimentos de milhões de reais.",
    "Atleta": "Você competia em um esporte individual ou coletivo, como natação ou futebol.",
    "Chef": "Você é um cozinheiro amador ou profissional.",
    "Chef do Outro Lado": "Você nunca foi muito bom na culinária convencional. Depois de sobreviver ao paranormal, entretanto, descobriu um talento que é considerado um grande tabu até mesmo pelos ocultistas mais experientes: cozinhar e ingerir entidades do Outro Lado.",
    "Colegial": "Você era um aluno do colegial e tinha uma rotina baseada nos estudos, nas amizades e nos dramas típicos de alguém da sua idade, até que um encontro com o paranormal mudou sua vida.",
    "Cosplayer": "Você é apaixonado pela arte do cosplay e dedicou sua vida a criar a melhor fantasia possível.",
    "Criminoso": "Você vivia uma vida fora da lei, seja como mero batedor de carteiras, seja como membro de uma facção criminosa.",
    "Cultista Arrependido": "Você fez parte de um culto paranormal. eja como for, algo abriu seus olhos e agora você luta pelo lado certo — embora carregue para sempre traços de sua vida pregressa.",
    "Desgarrado": "Você não vivia de acordo com as normas da sociedade. De qualquer forma, a vida sem os confortos modernos o deixou mais forte.",
    "Diplomata": "Você atuava em uma área onde as habilidades sociais e políticas eram ferramentas indispensáveis. Agora, você usa os contatos que adquiriu para combater o Outro Lado.",
    "Executivo": "Você possuía um trabalho de escritório em uma grande empresa, banco ou corporação.",
    "Explorador": "Você é uma pessoa que se interessa muito por his-tória ou geografia, frequentemente embarcando em trilhas e explorações para enriquecer seus estudos. ",
    "Experimento": "Você foi uma cobaia em um experimento físico. ",
    "Fanático por Criaturas": "Você sempre foi obcecado pelo sobrenatural. Desde que pode se lembrar, a ideia de encontrar uma criatura o fascina tanto quanto o assusta. ",
    "Fotógrafo": "Você é um artista visual que usa câmeras para capturar momentos e transmitir histórias através de imagens estáticas.",
    "Inventor Paranormal": "A curiosidade e a criatividade fizeram de você uma pessoa que busca constantemente desafiar limites e criar soluções inovadoras, sendo mais de uma vez intitulado como um “cientista louco”.",
    "Investigador": "Você era um investigador do governo, como um perito forense ou policial federal, ou privado, como um detetive particular.",
    "Jovem Místico": "Você possui uma profunda conexão com sua espiritualidade, suas crenças ou o próprio universo. ",
    "Legista do Turno da Noite": "Em um trabalho como o seu, é de se esperar que você já tenha visto muita coisa. Os sons que poderiam ter sido fruto de sua imaginação se revelaram mais do que um truque da sua própria mente, fazendo você descobrir que nem sempre a morte é o fim de tudo.",
    "Lutador": "Você pratica uma arte marcial ou esporte de luta, ou cresceu em um bairro perigoso onde aprendeu briga de rua.",
    "Magnata": "Você possui muito dinheiro ou patrimônio. Pode ser o herdeiro de uma família antiga ligada ao oculto, ter criado e vendido uma empresa e decidido usar sua riqueza para uma causa maior, ou ter ganho uma loteria após inadvertidamente escolher números amaldiçoados que formavam um ritual.",
    "Mateiro": "Você conhece áreas rurais e selvagens. Você pode ser um guia florestal, um biólogo de campo ou simples-mente um entusiasta da vida selvagem.",
    "Mercenário": "Você é um soldado de aluguel, que trabalha sozinho ou como parte de alguma organização que vende serviços militares.",
    "Mergulhador": "Seja por profissão ou por hobby, você é um aventureiro subaquático que explora os mistérios e maravilhas do mundo submerso.",
    "Militar": "Você serviu em uma força militar, como o exército ou a marinha. Passou muito tempo treinando com armas de fogo, até se tornar um perito no uso delas. ",
    "Motorista": "Você é um caminhoneiro, motorista de aplicativo, motoboy, piloto de corrida, motorista de ambulância ou qualquer outro tipo de condutor profissional. ",
    "Nerd Entusiasta": "Você dedicou muito do seu tempo aprendendo sobre videogames, RPGs de mesa, ficção científica ou qual-quer outro assunto considerado “nerd”. ",
    "Operário": "Pedreiro, industriário, operador de máquinas em uma fábrica. Você passou uma parte de sua vida em um emprego braçal, desempenhando atividades práticas que lhe deram uma visão pragmática do mundo.",
    "Policial": "Você fez parte de uma força de segurança pública, civil ou militar.",
    "Profetizado": "Como qualquer pessoa, você vai morrer. Entretanto, diferente delas, você sabe como isso vai acontecer. ",
    "Psicólogo": "Você se especializou no estudo e tratamento das questões mentais do ser humano.",
    "Religioso": "Você é devoto ou sacerdote de uma fé. Independentemente da religião que pratica, se dedica a auxiliar as pessoas com problemas espirituais. ",
    "Repórter Investigativo": "Você está sempre em busca de histórias significa-tivas, investigando eventos, entrevistando fontes e analisando dados para descobrir a verdade por trás dos acontecimentos. ",
    "Servidor Público": "Você possuía carreira em um órgão do governo, lidando com burocracia e atendendo pessoas.",
    "Teórico da Conspiração": "A humanidade nunca pisou na lua. Reptilianos ocupam importantes cargos públicos. A Terra é plana... E secretamente governada pelos Illuminati. Você sabe isso tudo, pois investigou a fundo esses importantes assuntos.",
    "T.I.": "Programador, engenheiro de software ou simplesmente “o cara da T.I.”, você tem treinamento e experiência para lidar com sistemas informatizados. ",
    "Trabalhador Rural": "Você trabalhava no campo ou em áreas isoladas, como fazendeiro, pescador, biólogo, veterinário.",
    "Trambiqueiro": "Uma vida digna exige muito trabalho, então é melhor nem tentar. Você vivia de pequenos golpes, jogatina ilegal e falcatruas.",
    "Universitário": "Você era aluno de uma faculdade. Em sua rotina de estudos, provas e festas, acabou descobrindo algo — talvez um livro amaldiçoado na antiga biblioteca do campus? ",
    "Vítima": "Em algum momento de sua vida — infância, juventude ou início da vida adulta — você encontrou o paranormal... E a experiência não foi nada boa."
}